"""
SQLAlchemy ORM models for causal models and edges.

These models map to the 'causal_models' and 'causal_edges' tables.

References:
    - Data model: specs/042-quantitative-analysis/data-model.md
    - SQLAlchemy 2.0: https://docs.sqlalchemy.org/en/20/orm/relationships.html
"""

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import JSON, DateTime, ForeignKey, ForeignKeyConstraint, Index, SmallInteger, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from synth_lab.models.orm.base import Base

# Fresh JSON type (not shared with MutableDict in base.py)
_JSONVariant = JSON().with_variant(JSONB(), "postgresql")

if TYPE_CHECKING:
    from synth_lab.models.orm.experiment import Experiment


class CausalModel(Base):
    """
    Causal model generated by LLM for an experiment.

    1:1 relationship with experiment (unique constraint on experiment_id).

    Attributes:
        id: Unique identifier (cm_[a-f0-9]{8})
        experiment_id: FK to experiments.id (unique)
        label: Model title generated by LLM
        intercept_mu: Intercept mean for simulation
        intercept_sigma: Intercept std dev for simulation
        nodes: JSON array of node names
        raw_llm_response: Full LLM response for debugging
    """

    __tablename__ = "causal_models"

    id: Mapped[str] = mapped_column(String(50), primary_key=True)
    experiment_id: Mapped[str] = mapped_column(
        String(50),
        ForeignKey("experiments.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    label: Mapped[str] = mapped_column(String(200), nullable=False)
    intercept_mu: Mapped[float] = mapped_column(nullable=False)
    intercept_sigma: Mapped[float] = mapped_column(nullable=False)
    nodes: Mapped[list] = mapped_column(_JSONVariant, nullable=False)
    raw_llm_response: Mapped[dict | None] = mapped_column(_JSONVariant, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    experiment: Mapped["Experiment"] = relationship("Experiment", foreign_keys=[experiment_id])
    edges: Mapped[list["CausalEdge"]] = relationship(
        "CausalEdge",
        back_populates="causal_model",
        cascade="all, delete-orphan",
        order_by="CausalEdge.id",
    )

    __table_args__ = (
        Index("idx_causal_models_experiment", "experiment_id"),
    )

    def __repr__(self) -> str:
        return f"<CausalModel(id={self.id!r}, experiment_id={self.experiment_id!r})>"


class CausalEdge(Base):
    """
    Edge in the causal DAG.

    Composite primary key: (id, causal_model_id).
    Each edge has 5 Likert options stored as JSON.

    Attributes:
        id: Edge identifier within the model (e.g., 'e1')
        causal_model_id: FK to causal_models.id
        from_node: Source node name
        to_node: Target node name
        user_var: Mapped userVar name
        direction: 1 (direct) or -1 (inverse)
        header: Contextual assertion header
        options: JSON array of 5 Likert options [{text, mu, sigma}]
        default_option: LLM-suggested default index
        selected_option: PM's selection (null = not answered)
    """

    __tablename__ = "causal_edges"

    id: Mapped[str] = mapped_column(String(50), primary_key=True)
    causal_model_id: Mapped[str] = mapped_column(
        String(50),
        ForeignKey("causal_models.id", ondelete="CASCADE"),
        primary_key=True,
    )
    from_node: Mapped[str] = mapped_column(String(50), nullable=False)
    to_node: Mapped[str] = mapped_column(String(50), nullable=False)
    user_var: Mapped[str] = mapped_column(String(30), nullable=False)
    direction: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    header: Mapped[str] = mapped_column(Text, nullable=False)
    options: Mapped[list] = mapped_column(_JSONVariant, nullable=False)
    default_option: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    selected_option: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)

    # Relationships
    causal_model: Mapped["CausalModel"] = relationship(
        "CausalModel",
        back_populates="edges",
    )

    __table_args__ = (
        ForeignKeyConstraint(
            ["causal_model_id"],
            ["causal_models.id"],
            ondelete="CASCADE",
            name="fk_causal_edges_model",
        ),
        Index("idx_causal_edges_model", "causal_model_id"),
    )

    def __repr__(self) -> str:
        return (
            f"<CausalEdge(id={self.id!r}, model={self.causal_model_id!r}, "
            f"{self.from_node!r} -> {self.to_node!r})>"
        )


if __name__ == "__main__":
    import sys

    all_validation_failures = []
    total_tests = 0

    total_tests += 1
    if CausalModel.__tablename__ != "causal_models":
        all_validation_failures.append(
            f"CausalModel table: {CausalModel.__tablename__}, expected 'causal_models'"
        )

    total_tests += 1
    if CausalEdge.__tablename__ != "causal_edges":
        all_validation_failures.append(
            f"CausalEdge table: {CausalEdge.__tablename__}, expected 'causal_edges'"
        )

    total_tests += 1
    cm_cols = set(CausalModel.__table__.columns.keys())
    required = {"id", "experiment_id", "label", "intercept_mu", "intercept_sigma", "nodes"}
    missing = required - cm_cols
    if missing:
        all_validation_failures.append(f"CausalModel missing columns: {missing}")

    total_tests += 1
    ce_cols = set(CausalEdge.__table__.columns.keys())
    required = {"id", "causal_model_id", "from_node", "to_node", "user_var", "direction",
                "header", "options", "default_option", "selected_option"}
    missing = required - ce_cols
    if missing:
        all_validation_failures.append(f"CausalEdge missing columns: {missing}")

    if all_validation_failures:
        print(f"VALIDATION FAILED - {len(all_validation_failures)} of {total_tests} tests failed:")
        for failure in all_validation_failures:
            print(f"  - {failure}")
        sys.exit(1)
    else:
        print(f"VALIDATION PASSED - All {total_tests} tests produced expected results")
        sys.exit(0)
