"""
Causal model entities for quantitative analysis.

Represents a causal DAG with nodes and edges, where each edge
is a Likert-scale assertion about variable relationships.

References:
    - Spec: specs/042-quantitative-analysis/spec.md
    - Data model: specs/042-quantitative-analysis/data-model.md
"""

from __future__ import annotations

import secrets
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field, field_validator

# Valid userVar values (10 fixed extractors)
VALID_USER_VARS = frozenset({
    "ageNorm",
    "incomeNorm",
    "eduNorm",
    "familySizeNorm",
    "hasVisualDisab",
    "hasMotorDisab",
    "digitalCapability",
    "riskAversion",
    "institutionalTrust",
    "frictionTolerance",
})


def generate_causal_model_id() -> str:
    """Generate a causal model ID with cm_ prefix and 8-char hex suffix."""
    return f"cm_{secrets.token_hex(4)}"


class LikertOption(BaseModel):
    """Single Likert option with hidden mu/sigma parameters."""

    text: str = Field(description="Self-contained assertion text in Portuguese BR.")
    mu: float = Field(ge=0.0, le=1.0, description="Coupling strength [0, 1].")
    sigma: float = Field(ge=0.0, le=1.0, description="Uncertainty fraction [0, 1].")


class CausalEdge(BaseModel):
    """
    Edge in the causal DAG.

    Each edge represents a causal assertion between two nodes,
    with 5 Likert options the PM evaluates.
    """

    id: str = Field(description="Edge identifier (e.g., 'e1', 'e2').")
    from_node: str = Field(max_length=50, description="Source node name.")
    to_node: str = Field(max_length=50, description="Target node name.")
    user_var: str = Field(description="Mapped userVar from synth attributes.")
    direction: int = Field(description="Relationship direction: 1 (direct) or -1 (inverse).")
    header: str = Field(max_length=300, description="Contextual header for the assertion.")
    options: list[LikertOption] = Field(description="Exactly 5 Likert options.")
    default_option: int = Field(ge=0, le=4, description="LLM-suggested default option index.")
    selected_option: int | None = Field(
        default=None,
        description="PM's selected option index (null = not answered).",
    )

    @field_validator("user_var")
    @classmethod
    def validate_user_var(cls, v: str) -> str:
        """Ensure userVar is one of the 10 valid values."""
        if v not in VALID_USER_VARS:
            raise ValueError(f"user_var must be one of {sorted(VALID_USER_VARS)}, got '{v}'")
        return v

    @field_validator("direction")
    @classmethod
    def validate_direction(cls, v: int) -> int:
        """Direction must be 1 or -1."""
        if v not in (1, -1):
            raise ValueError(f"direction must be 1 or -1, got {v}")
        return v

    @field_validator("options")
    @classmethod
    def validate_options_count(cls, v: list[LikertOption]) -> list[LikertOption]:
        """Must have exactly 5 options."""
        if len(v) != 5:
            raise ValueError(f"options must have exactly 5 items, got {len(v)}")
        return v

    @field_validator("selected_option")
    @classmethod
    def validate_selected_option(cls, v: int | None) -> int | None:
        """Selected option must be in [0, 4] when set."""
        if v is not None and (v < 0 or v > 4):
            raise ValueError(f"selected_option must be 0-4 or None, got {v}")
        return v


class CausalModel(BaseModel):
    """
    Causal model generated by LLM.

    Contains the DAG structure with nodes and metadata.
    Edges are stored separately but logically belong to this model.
    1:1 relationship with experiment.
    """

    id: str = Field(
        default_factory=generate_causal_model_id,
        pattern=r"^cm_[a-f0-9]{8}$",
        description="Unique causal model ID.",
    )
    experiment_id: str = Field(description="Parent experiment ID.")
    label: str = Field(max_length=200, description="Model title (LLM-generated).")
    intercept_mu: float = Field(ge=-3.0, le=3.0, description="Intercept mean [-3, 3].")
    intercept_sigma: float = Field(ge=0.1, le=1.0, description="Intercept std dev [0.1, 1].")
    nodes: list[str] = Field(description="DAG node names (7-10 items).")
    edges: list[CausalEdge] = Field(default_factory=list, description="DAG edges.")
    raw_llm_response: dict[str, Any] | None = Field(
        default=None, description="Raw LLM response for debugging."
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Creation timestamp.",
    )

    @field_validator("nodes")
    @classmethod
    def validate_nodes_count(cls, v: list[str]) -> list[str]:
        """Nodes list must have 7-10 items."""
        if len(v) < 7 or len(v) > 10:
            raise ValueError(f"nodes must have 7-10 items, got {len(v)}")
        return v


if __name__ == "__main__":
    import sys

    all_validation_failures = []
    total_tests = 0

    # Test 1: Generate ID
    total_tests += 1
    try:
        cm_id = generate_causal_model_id()
        if not cm_id.startswith("cm_"):
            all_validation_failures.append(f"ID should start with 'cm_': {cm_id}")
        if len(cm_id) != 11:
            all_validation_failures.append(f"ID should be 11 chars: {len(cm_id)}")
    except Exception as e:
        all_validation_failures.append(f"Generate ID failed: {e}")

    # Test 2: Create valid model
    total_tests += 1
    try:
        model = CausalModel(
            experiment_id="exp_12345678",
            label="Test Model",
            intercept_mu=0.1,
            intercept_sigma=0.4,
            nodes=["A", "B", "C", "D", "E", "F", "G"],
        )
        if not model.id.startswith("cm_"):
            all_validation_failures.append(f"Model ID invalid: {model.id}")
    except Exception as e:
        all_validation_failures.append(f"Create model failed: {e}")

    # Test 3: Valid edge
    total_tests += 1
    try:
        edge = CausalEdge(
            id="e1",
            from_node="Idade",
            to_node="Digital",
            user_var="ageNorm",
            direction=-1,
            header="Test header",
            options=[
                LikertOption(text=f"Option {i}", mu=0.8 - i * 0.15, sigma=0.15 + i * 0.05)
                for i in range(5)
            ],
            default_option=0,
        )
        if edge.selected_option is not None:
            all_validation_failures.append("selected_option should default to None")
    except Exception as e:
        all_validation_failures.append(f"Create edge failed: {e}")

    if all_validation_failures:
        print(f"VALIDATION FAILED - {len(all_validation_failures)} of {total_tests} tests failed:")
        for failure in all_validation_failures:
            print(f"  - {failure}")
        sys.exit(1)
    else:
        print(f"VALIDATION PASSED - All {total_tests} tests produced expected results")
        sys.exit(0)
