/**
 * API client for hypothesis wizard endpoints.
 *
 * Provides functions to initialize wizard and apply clarifications.
 *
 * References:
 * - Router: src/synth_lab/api/routers/hypotheses.py
 * - Spec: specs/036-simplified-hypothesis-wizard/spec.md
 */

import { fetchAPI } from './api';
import type { Hypothesis } from '@/types/hypothesis';

/**
 * Scenario profile for hypothesis generation.
 */
export type ScenarioProfile = 'conservative' | 'realistic' | 'optimistic';

/**
 * Request to initialize hypothesis wizard.
 */
export interface WizardInitRequest {
  scenario_profile: ScenarioProfile;
}

/**
 * Clarification question generated by wizard.
 */
export interface ClarificationQuestion {
  variable_name: string;
  question_text: string;
  criticality_score: number;
}

/**
 * Response from wizard initialization.
 */
export interface WizardInitResponse {
  hypotheses: Hypothesis[];
  clarification_questions: ClarificationQuestion[];
}

/**
 * Response type for clarification.
 */
export type ResponseType = 'more' | 'less' | 'equal' | 'dont_know';

/**
 * User response to a clarification question.
 */
export interface ClarificationResponse {
  variable_name: string;
  response: ResponseType;
}

/**
 * Request to apply clarification responses.
 */
export interface WizardClarifyRequest {
  responses: ClarificationResponse[];
}

/**
 * Response from clarification application.
 */
export interface WizardClarifyResponse {
  hypotheses: Hypothesis[];
}

/**
 * Initialize hypothesis wizard with scenario profile.
 *
 * Generates baseline hypotheses for all DAG variables using the selected
 * scenario profile (Conservative/Realistic/Optimistic).
 *
 * @param simulationId - Simulation ID
 * @param request - Wizard initialization request
 * @returns Generated hypotheses and clarification questions
 *
 * @example
 * const result = await initWizard('sim_12345678', {
 *   scenario_profile: 'realistic'
 * });
 */
export async function initWizard(
  simulationId: string,
  request: WizardInitRequest
): Promise<WizardInitResponse> {
  return fetchAPI(`/simulations/${simulationId}/hypotheses/wizard/init`, {
    method: 'POST',
    body: JSON.stringify(request),
  });
}

/**
 * Apply clarification responses to refine hypotheses.
 *
 * Adjusts hypothesis parameters based on qualitative user feedback
 * (more/less/equal/dont_know) to critical variables.
 *
 * @param simulationId - Simulation ID
 * @param request - Clarification responses
 * @returns Updated hypotheses
 *
 * @example
 * const result = await applyClarifications('sim_12345678', {
 *   responses: [
 *     { variable_name: 'Revenue', response: 'more' },
 *     { variable_name: 'Cost', response: 'less' }
 *   ]
 * });
 */
export async function applyClarifications(
  simulationId: string,
  request: WizardClarifyRequest
): Promise<WizardClarifyResponse> {
  return fetchAPI(`/simulations/${simulationId}/hypotheses/wizard/clarify`, {
    method: 'POST',
    body: JSON.stringify(request),
  });
}
