"""initial_schema

Revision ID: c5b57ad43acf
Revises: 
Create Date: 2026-01-20 13:07:19.975206
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'c5b57ad43acf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_insights',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('simulation_id', sa.String(length=50), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('response_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'insight_type', name='uq_chart_insights_sim_type')
    )
    op.create_index('idx_chart_insights_simulation', 'chart_insights', ['simulation_id'], unique=False)
    op.create_index('idx_chart_insights_type', 'chart_insights', ['insight_type'], unique=False)
    op.create_table('region_analyses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('simulation_id', sa.String(length=50), nullable=False),
    sa.Column('rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('synth_count', sa.Integer(), nullable=False),
    sa.Column('synth_percentage', sa.Float(), nullable=False),
    sa.Column('did_not_try_rate', sa.Float(), nullable=False),
    sa.Column('failed_rate', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('failure_delta', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regions_simulation', 'region_analyses', ['simulation_id'], unique=False)
    op.create_table('sensitivity_results',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('simulation_id', sa.String(length=50), nullable=False),
    sa.Column('analyzed_at', sa.String(length=50), nullable=False),
    sa.Column('deltas_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('baseline_success', sa.Float(), nullable=False),
    sa.Column('most_sensitive_dimension', sa.String(length=100), nullable=False),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensitivity_analyzed_at', 'sensitivity_results', ['analyzed_at'], unique=False)
    op.create_index('idx_sensitivity_simulation', 'sensitivity_results', ['simulation_id'], unique=False)
    op.create_table('synth_groups',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_synth_groups_config', 'synth_groups', ['config'], unique=False, postgresql_using='gin')
    op.create_index('idx_synth_groups_created', 'synth_groups', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_table('tags',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_tags_name', 'tags', ['name'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hypothesis', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('synth_group_id', sa.String(length=50), server_default='grp_00000001', nullable=False),
    sa.Column('scorecard_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['synth_group_id'], ['synth_groups.id'], ondelete='SET DEFAULT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_experiments_created', 'experiments', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_experiments_name', 'experiments', ['name'], unique=False)
    op.create_index('idx_experiments_status', 'experiments', ['status'], unique=False)
    op.create_index('idx_experiments_synth_group_id', 'experiments', ['synth_group_id'], unique=False)
    op.create_table('synths',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('synth_group_id', sa.String(length=50), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('link_photo', sa.Text(), nullable=True),
    sa.Column('avatar_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['synth_group_id'], ['synth_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_synths_created_at', 'synths', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_synths_group', 'synths', ['synth_group_id'], unique=False)
    op.create_index('idx_synths_nome', 'synths', ['nome'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('experiment_id', sa.String(length=50), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('total_synths', sa.Integer(), nullable=False),
    sa.Column('aggregated_outcomes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id')
    )
    op.create_index('idx_analysis_runs_experiment', 'analysis_runs', ['experiment_id'], unique=False)
    op.create_index('idx_analysis_runs_status', 'analysis_runs', ['status'], unique=False)
    op.create_table('experiment_documents',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('experiment_id', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('generated_at', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'document_type', 'source_id', name='uq_experiment_documents_exp_type_source')
    )
    op.create_index('idx_experiment_documents_experiment', 'experiment_documents', ['experiment_id'], unique=False)
    op.create_index('idx_experiment_documents_source', 'experiment_documents', ['source_id'], unique=False)
    op.create_index('idx_experiment_documents_status', 'experiment_documents', ['status'], unique=False)
    op.create_index('idx_experiment_documents_type', 'experiment_documents', ['document_type'], unique=False)
    op.create_table('experiment_materials',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('experiment_id', sa.String(length=50), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('material_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_status', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_experiment_materials_experiment', 'experiment_materials', ['experiment_id'], unique=False)
    op.create_index('idx_experiment_materials_order', 'experiment_materials', ['experiment_id', 'display_order'], unique=False)
    op.create_index('idx_experiment_materials_status', 'experiment_materials', ['description_status'], unique=False)
    op.create_index('idx_experiment_materials_type', 'experiment_materials', ['material_type'], unique=False)
    op.create_table('experiment_tags',
    sa.Column('experiment_id', sa.String(length=50), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experiment_id', 'tag_id')
    )
    op.create_index('idx_experiment_tags_experiment', 'experiment_tags', ['experiment_id'], unique=False)
    op.create_index('idx_experiment_tags_tag', 'experiment_tags', ['tag_id'], unique=False)
    op.create_table('interview_guide',
    sa.Column('experiment_id', sa.String(length=50), nullable=False),
    sa.Column('context_definition', sa.Text(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('context_examples', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_table('research_executions',
    sa.Column('exec_id', sa.String(length=100), nullable=False),
    sa.Column('experiment_id', sa.String(length=50), nullable=True),
    sa.Column('topic_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('synth_count', sa.Integer(), nullable=False),
    sa.Column('successful_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('additional_context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('exec_id')
    )
    op.create_index('idx_executions_experiment', 'research_executions', ['experiment_id'], unique=False)
    op.create_index('idx_executions_started', 'research_executions', ['started_at'], unique=False)
    op.create_index('idx_executions_status', 'research_executions', ['status'], unique=False)
    op.create_index('idx_executions_topic', 'research_executions', ['topic_name'], unique=False)
    op.create_table('analysis_cache',
    sa.Column('analysis_id', sa.String(length=50), nullable=False),
    sa.Column('cache_key', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('computed_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id', 'cache_key')
    )
    op.create_index('idx_analysis_cache_analysis', 'analysis_cache', ['analysis_id'], unique=False)
    op.create_table('explorations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('experiment_id', sa.String(length=50), nullable=False),
    sa.Column('baseline_analysis_id', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_depth', sa.Integer(), nullable=False),
    sa.Column('total_nodes', sa.Integer(), nullable=False),
    sa.Column('total_llm_calls', sa.Integer(), nullable=False),
    sa.Column('best_success_rate', sa.Float(), nullable=True),
    sa.Column('started_at', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['baseline_analysis_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_explorations_experiment', 'explorations', ['experiment_id'], unique=False)
    op.create_index('idx_explorations_status', 'explorations', ['status'], unique=False)
    op.create_table('synth_outcomes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('analysis_id', sa.String(length=50), nullable=False),
    sa.Column('synth_id', sa.String(length=50), nullable=False),
    sa.Column('did_not_try_rate', sa.Float(), nullable=False),
    sa.Column('failed_rate', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('synth_attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'synth_id', name='uq_synth_outcomes_analysis_synth')
    )
    op.create_index('idx_outcomes_analysis', 'synth_outcomes', ['analysis_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('exec_id', sa.String(length=100), nullable=False),
    sa.Column('synth_id', sa.String(length=50), nullable=False),
    sa.Column('synth_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['exec_id'], ['research_executions.exec_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exec_id', 'synth_id', name='uq_transcripts_exec_synth')
    )
    op.create_index('idx_transcripts_exec', 'transcripts', ['exec_id'], unique=False)
    op.create_index('idx_transcripts_synth', 'transcripts', ['synth_id'], unique=False)
    op.create_table('scenario_nodes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('exploration_id', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('action_applied', sa.Text(), nullable=True),
    sa.Column('action_category', sa.String(length=50), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('short_action', sa.String(length=200), nullable=True),
    sa.Column('scorecard_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('simulation_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('node_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['exploration_id'], ['explorations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['scenario_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scenario_nodes_depth', 'scenario_nodes', ['exploration_id', 'depth'], unique=False)
    op.create_index('idx_scenario_nodes_exploration', 'scenario_nodes', ['exploration_id'], unique=False)
    op.create_index('idx_scenario_nodes_parent', 'scenario_nodes', ['parent_id'], unique=False)
    op.create_index('idx_scenario_nodes_status', 'scenario_nodes', ['exploration_id', 'node_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scenario_nodes_status', table_name='scenario_nodes')
    op.drop_index('idx_scenario_nodes_parent', table_name='scenario_nodes')
    op.drop_index('idx_scenario_nodes_exploration', table_name='scenario_nodes')
    op.drop_index('idx_scenario_nodes_depth', table_name='scenario_nodes')
    op.drop_table('scenario_nodes')
    op.drop_index('idx_transcripts_synth', table_name='transcripts')
    op.drop_index('idx_transcripts_exec', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('idx_outcomes_analysis', table_name='synth_outcomes')
    op.drop_table('synth_outcomes')
    op.drop_index('idx_explorations_status', table_name='explorations')
    op.drop_index('idx_explorations_experiment', table_name='explorations')
    op.drop_table('explorations')
    op.drop_index('idx_analysis_cache_analysis', table_name='analysis_cache')
    op.drop_table('analysis_cache')
    op.drop_index('idx_executions_topic', table_name='research_executions')
    op.drop_index('idx_executions_status', table_name='research_executions')
    op.drop_index('idx_executions_started', table_name='research_executions')
    op.drop_index('idx_executions_experiment', table_name='research_executions')
    op.drop_table('research_executions')
    op.drop_table('interview_guide')
    op.drop_index('idx_experiment_tags_tag', table_name='experiment_tags')
    op.drop_index('idx_experiment_tags_experiment', table_name='experiment_tags')
    op.drop_table('experiment_tags')
    op.drop_index('idx_experiment_materials_type', table_name='experiment_materials')
    op.drop_index('idx_experiment_materials_status', table_name='experiment_materials')
    op.drop_index('idx_experiment_materials_order', table_name='experiment_materials')
    op.drop_index('idx_experiment_materials_experiment', table_name='experiment_materials')
    op.drop_table('experiment_materials')
    op.drop_index('idx_experiment_documents_type', table_name='experiment_documents')
    op.drop_index('idx_experiment_documents_status', table_name='experiment_documents')
    op.drop_index('idx_experiment_documents_source', table_name='experiment_documents')
    op.drop_index('idx_experiment_documents_experiment', table_name='experiment_documents')
    op.drop_table('experiment_documents')
    op.drop_index('idx_analysis_runs_status', table_name='analysis_runs')
    op.drop_index('idx_analysis_runs_experiment', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index('idx_synths_nome', table_name='synths')
    op.drop_index('idx_synths_group', table_name='synths')
    op.drop_index('idx_synths_created_at', table_name='synths', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('synths')
    op.drop_index('idx_experiments_synth_group_id', table_name='experiments')
    op.drop_index('idx_experiments_status', table_name='experiments')
    op.drop_index('idx_experiments_name', table_name='experiments')
    op.drop_index('idx_experiments_created', table_name='experiments', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('experiments')
    op.drop_index('idx_tags_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index('idx_synth_groups_created', table_name='synth_groups', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_synth_groups_config', table_name='synth_groups', postgresql_using='gin')
    op.drop_table('synth_groups')
    op.drop_index('idx_sensitivity_simulation', table_name='sensitivity_results')
    op.drop_index('idx_sensitivity_analyzed_at', table_name='sensitivity_results')
    op.drop_table('sensitivity_results')
    op.drop_index('idx_regions_simulation', table_name='region_analyses')
    op.drop_table('region_analyses')
    op.drop_index('idx_chart_insights_type', table_name='chart_insights')
    op.drop_index('idx_chart_insights_simulation', table_name='chart_insights')
    op.drop_table('chart_insights')
    # ### end Alembic commands ###
