"""add mechanism and feature type tables for narrative config

Revision ID: 02b244484459
Revises: d9653ccb9a1a
Create Date: 2026-02-05 10:47:48.168095
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '02b244484459'
down_revision: Union[str, None] = 'd9653ccb9a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulated_worlds_simulation_id'), table_name='simulated_worlds')
    op.drop_table('simulated_worlds')
    op.drop_index(op.f('ix_causal_dags_simulation_id'), table_name='causal_dags')
    op.drop_table('causal_dags')
    op.drop_index(op.f('idx_mechanism_definitions_key'), table_name='mechanism_definitions')
    op.drop_table('mechanism_definitions')
    op.drop_index(op.f('ix_variables_dag_id'), table_name='variables')
    op.drop_table('variables')
    op.drop_index(op.f('ix_insights_simulation_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_simulations_created_at'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_status'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_hypothesis_versions_simulation_id'), table_name='hypothesis_versions')
    op.drop_table('hypothesis_versions')
    op.drop_index(op.f('ix_audit_trails_simulation_id'), table_name='audit_trails')
    op.drop_table('audit_trails')
    op.drop_index(op.f('ix_hypotheses_simulation_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('idx_mechanism_options_mechanism_id'), table_name='mechanism_options')
    op.drop_index(op.f('idx_mechanism_options_order'), table_name='mechanism_options')
    op.drop_table('mechanism_options')
    op.drop_index(op.f('idx_feature_types_key'), table_name='feature_types')
    op.drop_table('feature_types')
    op.drop_index(op.f('idx_experiments_created'), table_name='experiments')
    op.create_index('idx_experiments_created', 'experiments', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_synth_groups_created'), table_name='synth_groups')
    op.create_index('idx_synth_groups_created', 'synth_groups', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_synths_created_at'), table_name='synths')
    op.create_index('idx_synths_created_at', 'synths', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_synths_created_at', table_name='synths', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_synths_created_at'), 'synths', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_synth_groups_created', table_name='synth_groups', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_synth_groups_created'), 'synth_groups', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_experiments_created', table_name='experiments', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_experiments_created'), 'experiments', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('feature_types',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label_pt', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amplifies_mechanisms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('feature_types_pkey')),
    sa.UniqueConstraint('key', name=op.f('feature_types_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_feature_types_key'), 'feature_types', ['key'], unique=True)
    op.create_table('mechanism_options',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mechanism_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('value >= 0::numeric AND value <= 1::numeric', name=op.f('check_mechanism_option_value_range')),
    sa.ForeignKeyConstraint(['mechanism_id'], ['mechanism_definitions.id'], name=op.f('mechanism_options_mechanism_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mechanism_options_pkey'))
    )
    op.create_index(op.f('idx_mechanism_options_order'), 'mechanism_options', ['mechanism_id', 'display_order'], unique=True)
    op.create_index(op.f('idx_mechanism_options_mechanism_id'), 'mechanism_options', ['mechanism_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('simulation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('variable_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('distribution_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('distribution_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('range_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('range_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('correlations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('variable_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('scenario_options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('selected_scenario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('relevance', sa.VARCHAR(length=10), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('hypotheses_simulation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], name=op.f('hypotheses_variable_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hypotheses_pkey'))
    )
    op.create_index(op.f('ix_hypotheses_simulation_id'), 'hypotheses', ['simulation_id'], unique=False)
    op.create_table('audit_trails',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('simulation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dag_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('hypotheses_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('random_seed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('evidence_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('insights_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('audit_trails_simulation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_trails_pkey'))
    )
    op.create_index(op.f('ix_audit_trails_simulation_id'), 'audit_trails', ['simulation_id'], unique=False)
    op.create_table('hypothesis_versions',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('simulation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dag_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('hypotheses_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('hypothesis_versions_simulation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hypothesis_versions_pkey')),
    sa.UniqueConstraint('simulation_id', 'version_name', name=op.f('uq_simulation_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_hypothesis_versions_simulation_id'), 'hypothesis_versions', ['simulation_id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('problem_decomposition', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('random_seed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('n_worlds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='simulations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_simulations_status'), 'simulations', ['status'], unique=False)
    op.create_index(op.f('ix_simulations_created_at'), 'simulations', ['created_at'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('simulation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('insight_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('insights_simulation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('insights_pkey'))
    )
    op.create_index(op.f('ix_insights_simulation_id'), 'insights', ['simulation_id'], unique=False)
    op.create_table('variables',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dag_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('controllable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('controllability', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_intervention', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_outcome', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_critical_uncertainty', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('position_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('position_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dag_id'], ['causal_dags.id'], name=op.f('variables_dag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('variables_pkey'))
    )
    op.create_index(op.f('ix_variables_dag_id'), 'variables', ['dag_id'], unique=False)
    op.create_table('mechanism_definitions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label_pt', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mechanism_definitions_pkey')),
    sa.UniqueConstraint('key', name=op.f('mechanism_definitions_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_mechanism_definitions_key'), 'mechanism_definitions', ['key'], unique=True)
    op.create_table('causal_dags',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('simulation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('causal_dags_simulation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('causal_dags_pkey'))
    )
    op.create_index(op.f('ix_causal_dags_simulation_id'), 'causal_dags', ['simulation_id'], unique=False)
    op.create_table('simulated_worlds',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('simulation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('world_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('world_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('outcome_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('simulated_worlds_simulation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('simulated_worlds_pkey'))
    )
    op.create_index(op.f('ix_simulated_worlds_simulation_id'), 'simulated_worlds', ['simulation_id'], unique=False)
    # ### end Alembic commands ###
