"""fix: update research_executions index on started_at column

Revision ID: 7064b7bb965d
Revises: f28fd615d2a9
Create Date: 2026-01-03 17:37:34.114246
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '7064b7bb965d'
down_revision: Union[str, None] = 'f28fd615d2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_executions_started'), table_name='research_executions')
    op.create_index('idx_executions_started', 'research_executions', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_executions_started', table_name='research_executions', postgresql_ops={'started_at': 'DESC'})
    op.create_index(op.f('idx_executions_started'), 'research_executions', [sa.literal_column('started_at DESC')], unique=False)
    # ### end Alembic commands ###
