"""fix: simplify idx_executions_started index definition

Revision ID: e5d26c38a962
Revises: 7064b7bb965d
Create Date: 2026-01-03 17:38:52.883745
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'e5d26c38a962'
down_revision: Union[str, None] = '7064b7bb965d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_executions_started'), table_name='research_executions')
    op.create_index('idx_executions_started', 'research_executions', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_executions_started', table_name='research_executions')
    op.create_index(op.f('idx_executions_started'), 'research_executions', [sa.literal_column('started_at DESC')], unique=False)
    # ### end Alembic commands ###
