"""Sync schema: fix started_at index and messages column type

Revision ID: 103d7ca69596
Revises: c65e0b6ff583
Create Date: 2026-01-03 16:35:55.718660
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '103d7ca69596'
down_revision: Union[str, None] = 'c65e0b6ff583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_executions_started'), table_name='research_executions')
    op.create_index('idx_executions_started', 'research_executions', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.alter_column('transcripts', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcripts', 'messages',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_executions_started', table_name='research_executions', postgresql_ops={'started_at': 'DESC'})
    op.create_index(op.f('idx_executions_started'), 'research_executions', [sa.literal_column('started_at DESC')], unique=False)
    # ### end Alembic commands ###
