"""Fix index definitions on created_at columns

Revision ID: 58b0dafa7483
Revises: e5d26c38a962
Create Date: 2026-01-04 21:24:53.834516
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '58b0dafa7483'
down_revision: Union[str, None] = 'e5d26c38a962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_experiments_created'), table_name='experiments')
    op.create_index('idx_experiments_created', 'experiments', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_synth_groups_created'), table_name='synth_groups')
    op.create_index('idx_synth_groups_created', 'synth_groups', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_synths_created_at'), table_name='synths')
    op.create_index('idx_synths_created_at', 'synths', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_synths_created_at', table_name='synths', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_synths_created_at'), 'synths', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_synth_groups_created', table_name='synth_groups', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_synth_groups_created'), 'synth_groups', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_experiments_created', table_name='experiments', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_experiments_created'), 'experiments', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
