"""fix: resolve schema divergence in causal_dags and feature_types

Revision ID: 21d9e0896964
Revises: d9653ccb9a1a
Create Date: 2026-02-05 14:26:45.238632
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '21d9e0896964'
down_revision: Union[str, None] = 'd9653ccb9a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('causal_dags', 'nodes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('causal_dags', 'edges',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('causal_dags', 'assumptions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('causal_dags', 'risks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_experiments_created'), table_name='experiments')
    op.create_index('idx_experiments_created', 'experiments', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_constraint(op.f('feature_types_key_key'), 'feature_types', type_='unique')
    op.drop_index(op.f('idx_feature_types_key'), table_name='feature_types')
    op.create_index(op.f('ix_feature_types_key'), 'feature_types', ['key'], unique=True)
    op.alter_column('hypotheses', 'correlations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('hypotheses', 'scenario_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('hypotheses', 'selected_scenario',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_simulation_version'), 'hypothesis_versions', type_='unique')
    op.alter_column('insights', 'recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_mechanism_definitions_key'), table_name='mechanism_definitions')
    op.drop_constraint(op.f('mechanism_definitions_key_key'), 'mechanism_definitions', type_='unique')
    op.create_index(op.f('ix_mechanism_definitions_key'), 'mechanism_definitions', ['key'], unique=True)
    op.drop_index(op.f('idx_mechanism_options_mechanism_id'), table_name='mechanism_options')
    op.drop_index(op.f('idx_mechanism_options_order'), table_name='mechanism_options')
    op.create_index(op.f('ix_mechanism_options_mechanism_id'), 'mechanism_options', ['mechanism_id'], unique=False)
    op.drop_index(op.f('idx_synth_groups_created'), table_name='synth_groups')
    op.create_index('idx_synth_groups_created', 'synth_groups', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_synths_created_at'), table_name='synths')
    op.create_index('idx_synths_created_at', 'synths', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_synths_created_at', table_name='synths', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_synths_created_at'), 'synths', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_synth_groups_created', table_name='synth_groups', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_synth_groups_created'), 'synth_groups', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_mechanism_options_mechanism_id'), table_name='mechanism_options')
    op.create_index(op.f('idx_mechanism_options_order'), 'mechanism_options', ['mechanism_id', 'display_order'], unique=True)
    op.create_index(op.f('idx_mechanism_options_mechanism_id'), 'mechanism_options', ['mechanism_id'], unique=False)
    op.drop_index(op.f('ix_mechanism_definitions_key'), table_name='mechanism_definitions')
    op.create_unique_constraint(op.f('mechanism_definitions_key_key'), 'mechanism_definitions', ['key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_mechanism_definitions_key'), 'mechanism_definitions', ['key'], unique=True)
    op.alter_column('insights', 'recommendations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_simulation_version'), 'hypothesis_versions', ['simulation_id', 'version_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('hypotheses', 'selected_scenario',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('hypotheses', 'scenario_options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('hypotheses', 'correlations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_feature_types_key'), table_name='feature_types')
    op.create_index(op.f('idx_feature_types_key'), 'feature_types', ['key'], unique=True)
    op.create_unique_constraint(op.f('feature_types_key_key'), 'feature_types', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_experiments_created', table_name='experiments', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_experiments_created'), 'experiments', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('causal_dags', 'risks',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('causal_dags', 'assumptions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('causal_dags', 'edges',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('causal_dags', 'nodes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
