"""Remove obsolete feature_scorecards and simulation_runs tables

Revision ID: 553590ab1de1
Revises: 58b0dafa7483
Create Date: 2026-01-04 21:56:37.699636
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '553590ab1de1'
down_revision: Union[str, None] = '58b0dafa7483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop simulation_runs first (has FK to feature_scorecards)
    op.drop_index(op.f('idx_simulations_scorecard'), table_name='simulation_runs')
    op.drop_index(op.f('idx_simulations_status'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    # Then drop feature_scorecards
    op.drop_index(op.f('idx_scorecards_experiment'), table_name='feature_scorecards')
    op.drop_table('feature_scorecards')
    # NOTE: Index fixes for created_at columns were already applied in migration 58b0dafa7483
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create feature_scorecards first (no dependencies)
    op.create_table('feature_scorecards',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('feature_scorecards_experiment_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('feature_scorecards_pkey'))
    )
    op.create_index(op.f('idx_scorecards_experiment'), 'feature_scorecards', ['experiment_id'], unique=False)
    # Then create simulation_runs (has FK to feature_scorecards)
    op.create_table('simulation_runs',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scorecard_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('started_at', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('completed_at', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('scenario_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_synths', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aggregated_outcomes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('execution_time_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scorecard_id'], ['feature_scorecards.id'], name=op.f('simulation_runs_scorecard_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('simulation_runs_pkey'))
    )
    op.create_index(op.f('idx_simulations_status'), 'simulation_runs', ['status'], unique=False)
    op.create_index(op.f('idx_simulations_scorecard'), 'simulation_runs', ['scorecard_id'], unique=False)
    # NOTE: Index changes for created_at columns are handled by migration 58b0dafa7483
    # ### end Alembic commands ###
