"""fix share tables and missing owner_id constraints

Revision ID: 3cc6321a86c9
Revises: a7b8c9d0e1f2
Create Date: 2026-01-22 18:31:39.304392
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '3cc6321a86c9'
down_revision: Union[str, None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_experiment_shares_experiment'), table_name='experiment_shares')
    op.drop_index(op.f('idx_experiment_shares_user'), table_name='experiment_shares')
    op.drop_constraint(op.f('uq_experiment_user_share'), 'experiment_shares', type_='unique')
    op.create_index(op.f('ix_experiment_shares_experiment_id'), 'experiment_shares', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_shares_user_id'), 'experiment_shares', ['user_id'], unique=False)
    op.drop_index(op.f('idx_experiments_owner'), table_name='experiments')
    op.drop_index(op.f('idx_experiments_created'), table_name='experiments')
    op.create_index('idx_experiments_created', 'experiments', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_experiments_owner_id'), 'experiments', ['owner_id'], unique=False)
    op.drop_index(op.f('idx_synth_group_shares_synth_group'), table_name='synth_group_shares')
    op.drop_index(op.f('idx_synth_group_shares_user'), table_name='synth_group_shares')
    op.drop_constraint(op.f('uq_synth_group_user_share'), 'synth_group_shares', type_='unique')
    op.create_index(op.f('ix_synth_group_shares_synth_group_id'), 'synth_group_shares', ['synth_group_id'], unique=False)
    op.create_index(op.f('ix_synth_group_shares_user_id'), 'synth_group_shares', ['user_id'], unique=False)
    op.drop_index(op.f('idx_synth_groups_owner'), table_name='synth_groups')
    op.drop_index(op.f('idx_synth_groups_created'), table_name='synth_groups')
    op.create_index('idx_synth_groups_created', 'synth_groups', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_synth_groups_owner_id'), 'synth_groups', ['owner_id'], unique=False)
    op.drop_index(op.f('idx_synths_created_at'), table_name='synths')
    op.create_index('idx_synths_created_at', 'synths', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.alter_column('users', 'updated_at',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_google_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_google_user_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_user_id'), 'users', ['google_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_google_user_id_key'), 'users', ['google_user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_google_id'), 'users', ['google_user_id'], unique=True)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index('idx_synths_created_at', table_name='synths', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_synths_created_at'), 'synths', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_synth_groups_owner_id'), table_name='synth_groups')
    op.drop_index('idx_synth_groups_created', table_name='synth_groups', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_synth_groups_created'), 'synth_groups', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_synth_groups_owner'), 'synth_groups', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_synth_group_shares_user_id'), table_name='synth_group_shares')
    op.drop_index(op.f('ix_synth_group_shares_synth_group_id'), table_name='synth_group_shares')
    op.create_unique_constraint(op.f('uq_synth_group_user_share'), 'synth_group_shares', ['synth_group_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_synth_group_shares_user'), 'synth_group_shares', ['user_id'], unique=False)
    op.create_index(op.f('idx_synth_group_shares_synth_group'), 'synth_group_shares', ['synth_group_id'], unique=False)
    op.drop_index(op.f('ix_experiments_owner_id'), table_name='experiments')
    op.drop_index('idx_experiments_created', table_name='experiments', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_experiments_created'), 'experiments', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_experiments_owner'), 'experiments', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_experiment_shares_user_id'), table_name='experiment_shares')
    op.drop_index(op.f('ix_experiment_shares_experiment_id'), table_name='experiment_shares')
    op.create_unique_constraint(op.f('uq_experiment_user_share'), 'experiment_shares', ['experiment_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_experiment_shares_user'), 'experiment_shares', ['user_id'], unique=False)
    op.create_index(op.f('idx_experiment_shares_experiment'), 'experiment_shares', ['experiment_id'], unique=False)
    # ### end Alembic commands ###
