"""add_synth_selection_type_to_research_executions

Revision ID: df69409340e0
Revises: ce8298d5f150
Create Date: 2026-02-24 13:36:32.591258
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'df69409340e0'
down_revision: Union[str, None] = 'ce8298d5f150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_interpretations', 'model',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_experiments_created'), table_name='experiments')
    op.create_index('idx_experiments_created', 'experiments', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.add_column('research_executions', sa.Column('synth_selection_type', sa.String(length=50), nullable=True))
    op.alter_column('simulation_runs', 'n_iterations',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_simulation_runs_created'), table_name='simulation_runs')
    op.create_index('idx_simulation_runs_created', 'simulation_runs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_synth_groups_created'), table_name='synth_groups')
    op.create_index('idx_synth_groups_created', 'synth_groups', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_synths_created_at'), table_name='synths')
    op.create_index('idx_synths_created_at', 'synths', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_synths_created_at', table_name='synths', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_synths_created_at'), 'synths', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_synth_groups_created', table_name='synth_groups', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_synth_groups_created'), 'synth_groups', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_simulation_runs_created', table_name='simulation_runs', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_simulation_runs_created'), 'simulation_runs', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('simulation_runs', 'n_iterations',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3000'),
               existing_nullable=False)
    op.drop_column('research_executions', 'synth_selection_type')
    op.drop_index('idx_experiments_created', table_name='experiments', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_experiments_created'), 'experiments', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('analysis_interpretations', 'model',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'gpt-4o-mini'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
