"""
Insights API Router for AI-generated chart insights and executive summaries.

Provides endpoints for retrieving chart-specific insights and executive summaries
generated by LLM from quantitative analysis data.

References:
    - Services: src/synth_lab/services/insight_service.py, executive_summary_service.py
    - Entities: src/synth_lab/domain/entities/chart_insight.py, executive_summary.py
    - Spec: specs/023-quantitative-ai-insights/spec.md (User Story 1, 2)

Endpoints:
    GET /experiments/{experiment_id}/insights/{chart_type} - Get specific chart insight
    GET /experiments/{experiment_id}/insights - Get all insights with stats
    GET /experiments/{experiment_id}/insights/executive-summary - Get executive summary
"""

from fastapi import APIRouter, BackgroundTasks, HTTPException, status
from pydantic import BaseModel, Field

from synth_lab.domain.entities.chart_insight import ChartInsight
from synth_lab.domain.entities.executive_summary import ExecutiveSummary
from synth_lab.repositories.analysis_cache_repository import AnalysisCacheRepository
from synth_lab.repositories.analysis_repository import AnalysisRepository
from synth_lab.repositories.experiment_repository import ExperimentRepository
from synth_lab.services.insight_service import InsightService

router = APIRouter()


# Request models
class GenerateInsightRequest(BaseModel):
    """Request to generate insight for a chart."""

    chart_type: str = Field(description="Chart type to generate insight for")
    chart_data: dict = Field(description="Chart data for insight generation")


# Response models
class AllInsightsStatsResponse(BaseModel):
    """Statistics about insights for an analysis."""

    total_charts: int = Field(description="Total charts analyzed")
    completed_insights: int = Field(description="Insights successfully generated")
    pending_insights: int = Field(description="Insights being generated")
    failed_insights: int = Field(description="Insights that failed")


class AllInsightsResponse(BaseModel):
    """Response with all insights and statistics."""

    analysis_id: str
    insights: list[ChartInsight]
    executive_summary: ExecutiveSummary | None
    stats: AllInsightsStatsResponse


# Helper functions
def get_experiment_repo() -> ExperimentRepository:
    """Get experiment repository instance."""
    return ExperimentRepository()


def get_analysis_repo() -> AnalysisRepository:
    """Get analysis repository instance."""
    return AnalysisRepository()


def get_cache_repo() -> AnalysisCacheRepository:
    """Get cache repository instance."""
    return AnalysisCacheRepository()


# Endpoints
# NOTE: More specific routes MUST come before parameterized routes in FastAPI

@router.post(
    "/{experiment_id}/analysis/insights/{chart_type}",
    response_model=ChartInsight,
    summary="Generate chart insight",
    description="Generate or regenerate AI insight for a specific chart",
)
async def generate_chart_insight(
    experiment_id: str,
    chart_type: str,
    request: GenerateInsightRequest,
    background_tasks: BackgroundTasks,
) -> ChartInsight:
    """
    Generate insight for a specific chart type.

    This endpoint triggers insight generation using the InsightService.
    The insight generation runs in the background and returns immediately
    with a "pending" status. The actual insight will be generated asynchronously.

    Args:
        experiment_id: Experiment ID
        chart_type: Chart type (try_vs_success, shap_summary, etc.)
        request: Chart data for insight generation
        background_tasks: FastAPI background tasks

    Returns:
        ChartInsight with "pending" status initially

    Raises:
        404: If experiment or analysis not found
        400: If chart_type is invalid
    """
    # Validate chart type
    valid_chart_types = [
        "try_vs_success",
        "distribution",
        "shap_summary",
        "pdp",
        "pca_scatter",
        "radar_comparison",
        "extreme_cases",
        "outliers",
    ]
    if chart_type not in valid_chart_types:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid chart_type. Must be one of: {', '.join(valid_chart_types)}",
        )

    # Get experiment and analysis
    exp_repo = get_experiment_repo()
    ana_repo = get_analysis_repo()

    experiment = exp_repo.get_by_id(experiment_id)
    if experiment is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Experiment {experiment_id} not found",
        )

    analysis = ana_repo.get_by_experiment_id(experiment_id)
    if analysis is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No analysis found for experiment {experiment_id}",
        )

    # Create pending insight immediately
    insight_service = InsightService()
    pending_insight = insight_service._create_pending_insight(
        analysis.id, chart_type
    )

    # Generate insight in background
    def generate_insight_task():
        try:
            insight_service.generate_insight(
                analysis.id, chart_type, request.chart_data
            )
        except Exception as e:
            # Log error but don't fail the request
            from loguru import logger

            logger.error(
                f"Background insight generation failed for {chart_type}: {e}"
            )

    background_tasks.add_task(generate_insight_task)

    return pending_insight


@router.get(
    "/{experiment_id}/insights/executive-summary",
    response_model=ExecutiveSummary,
    summary="Get executive summary",
    description="Retrieve executive summary synthesizing all chart insights",
)
async def get_executive_summary(experiment_id: str) -> ExecutiveSummary:
    """
    Get executive summary for an experiment.

    Args:
        experiment_id: Experiment ID

    Returns:
        ExecutiveSummary synthesizing all insights

    Raises:
        404: If experiment, analysis, or summary not found
    """
    # Get experiment and analysis
    exp_repo = get_experiment_repo()
    ana_repo = get_analysis_repo()
    cache_repo = get_cache_repo()

    experiment = exp_repo.get_by_id(experiment_id)
    if experiment is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Experiment {experiment_id} not found",
        )

    analysis = ana_repo.get_by_experiment_id(experiment_id)
    if analysis is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No analysis found for experiment {experiment_id}",
        )

    # Get executive summary
    summary = cache_repo.get_executive_summary(analysis.id)
    if summary is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Executive summary not found. Run analysis to generate summary.",
        )

    return summary


@router.get(
    "/{experiment_id}/insights/{chart_type}",
    response_model=ChartInsight,
    summary="Get chart-specific insight",
    description="Retrieve AI-generated insight for a specific chart type",
)
async def get_chart_insight(
    experiment_id: str,
    chart_type: str,
) -> ChartInsight:
    """
    Get insight for a specific chart type.

    Args:
        experiment_id: Experiment ID
        chart_type: Chart type (try_vs_success, shap_summary, pdp, pca_scatter, etc.)

    Returns:
        ChartInsight for the requested chart type

    Raises:
        404: If experiment or analysis not found
        404: If insight not found
        400: If chart_type is invalid
    """
    # Validate chart type
    valid_chart_types = [
        "try_vs_success",
        "shap_summary",
        "pdp",
        "pca_scatter",
        "radar_comparison",
        "extreme_cases",
        "outliers",
    ]
    if chart_type not in valid_chart_types:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid chart_type. Must be one of: {', '.join(valid_chart_types)}",
        )

    # Get experiment and analysis
    exp_repo = get_experiment_repo()
    ana_repo = get_analysis_repo()
    cache_repo = get_cache_repo()

    experiment = exp_repo.get_by_id(experiment_id)
    if experiment is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Experiment {experiment_id} not found",
        )

    analysis = ana_repo.get_by_experiment_id(experiment_id)
    if analysis is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No analysis found for experiment {experiment_id}",
        )

    # Get insight from cache
    insight = cache_repo.get_chart_insight(analysis.id, chart_type)
    if insight is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Insight not found for chart type '{chart_type}'. Run analysis to generate insights.",
        )

    return insight


@router.get(
    "/{experiment_id}/insights",
    response_model=AllInsightsResponse,
    summary="Get all insights",
    description="Retrieve all chart insights and executive summary with statistics",
)
async def get_all_insights(experiment_id: str) -> AllInsightsResponse:
    """
    Get all insights for an experiment with statistics.

    Args:
        experiment_id: Experiment ID

    Returns:
        All insights, executive summary, and stats

    Raises:
        404: If experiment or analysis not found
    """
    # Get experiment and analysis
    exp_repo = get_experiment_repo()
    ana_repo = get_analysis_repo()
    cache_repo = get_cache_repo()

    experiment = exp_repo.get_by_id(experiment_id)
    if experiment is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Experiment {experiment_id} not found",
        )

    analysis = ana_repo.get_by_experiment_id(experiment_id)
    if analysis is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No analysis found for experiment {experiment_id}",
        )

    # Get all insights
    insights = cache_repo.get_all_chart_insights(analysis.id)
    summary = cache_repo.get_executive_summary(analysis.id)

    # Calculate statistics
    total_expected = 7  # 7 supported chart types
    completed = len([i for i in insights if i.status == "completed"])
    pending = len([i for i in insights if i.status == "pending"])
    failed = len([i for i in insights if i.status == "failed"])

    stats = AllInsightsStatsResponse(
        total_charts=total_expected,
        completed_insights=completed,
        pending_insights=pending,
        failed_insights=failed,
    )

    return AllInsightsResponse(
        analysis_id=analysis.id,
        insights=insights,
        executive_summary=summary,
        stats=stats,
    )


if __name__ == "__main__":
    import sys

    all_validation_failures = []
    total_tests = 0

    # Test 1: Router has routes
    total_tests += 1
    try:
        if len(router.routes) < 3:
            all_validation_failures.append(f"Expected at least 3 routes, got {len(router.routes)}")
    except Exception as e:
        all_validation_failures.append(f"Router routes test failed: {e}")

    # Test 2: Check route paths
    total_tests += 1
    try:
        paths = [r.path for r in router.routes]
        expected_paths = [
            "/{experiment_id}/insights/{chart_type}",
            "/{experiment_id}/insights",
            "/{experiment_id}/insights/executive-summary",
        ]
        missing = [p for p in expected_paths if p not in paths]
        if missing:
            all_validation_failures.append(f"Missing routes: {missing}")
    except Exception as e:
        all_validation_failures.append(f"Route paths test failed: {e}")

    # Final validation result
    if all_validation_failures:
        print(f"❌ VALIDATION FAILED - {len(all_validation_failures)} of {total_tests} tests failed:")
        for failure in all_validation_failures:
            print(f"  - {failure}")
        sys.exit(1)
    else:
        print(f"✅ VALIDATION PASSED - All {total_tests} tests produced expected results")
        print("Insights router is validated and ready for use")
        sys.exit(0)
