openapi: 3.0.3
info:
  title: Interview API
  description: API para entrevistas com synths (N:1 com experimento) e SSE streaming
  version: 2.0.0

paths:
  /experiments/{experiment_id}/interviews:
    get:
      summary: Listar entrevistas do experimento
      operationId: listInterviews
      parameters:
        - name: experiment_id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Lista de entrevistas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterviewListResponse'
        '404':
          description: Experimento não encontrado

    post:
      summary: Criar nova rodada de entrevistas
      description: Inicia uma nova rodada de entrevistas para o experimento
      operationId: createInterview
      parameters:
        - name: experiment_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InterviewCreate'
      responses:
        '202':
          description: Entrevista iniciada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterviewResponse'
        '404':
          description: Experimento não encontrado

  /research/{exec_id}:
    get:
      summary: Obter detalhes da entrevista
      operationId: getInterview
      parameters:
        - name: exec_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes da entrevista
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterviewDetailResponse'
        '404':
          description: Entrevista não encontrada

  /research/{exec_id}/stream:
    get:
      summary: Stream SSE de mensagens
      description: |
        Server-Sent Events para acompanhamento em tempo real das entrevistas.

        **Eventos:**
        - `message`: Nova mensagem do entrevistador ou synth
        - `interview_completed`: Entrevista com um synth finalizada
        - `transcription_completed`: Todas entrevistas finalizadas
        - `execution_completed`: Processamento completo (inclui geração de resumo)

        **Replay:** Se a entrevista já estiver em andamento, o stream envia
        primeiro todas as mensagens históricas antes de começar o streaming
        em tempo real.
      operationId: streamInterview
      parameters:
        - name: exec_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Stream SSE
          content:
            text/event-stream:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/MessageEvent'
                  - $ref: '#/components/schemas/InterviewCompletedEvent'
                  - $ref: '#/components/schemas/TranscriptionCompletedEvent'
                  - $ref: '#/components/schemas/ExecutionCompletedEvent'
        '404':
          description: Entrevista não encontrada

  /research/{exec_id}/transcripts:
    get:
      summary: Listar transcrições
      operationId: listTranscripts
      parameters:
        - name: exec_id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Lista de transcrições
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranscriptListResponse'

  /research/{exec_id}/transcripts/{synth_id}:
    get:
      summary: Obter transcrição específica
      operationId: getTranscript
      parameters:
        - name: exec_id
          in: path
          required: true
          schema:
            type: string
        - name: synth_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transcrição do synth
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranscriptResponse'
        '404':
          description: Transcrição não encontrada

  /research/{exec_id}/summary:
    get:
      summary: Obter resumo da entrevista
      operationId: getSummary
      parameters:
        - name: exec_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Resumo em markdown
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
        '404':
          description: Resumo não encontrado

    post:
      summary: Gerar resumo
      operationId: generateSummary
      parameters:
        - name: exec_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '202':
          description: Geração iniciada
        '404':
          description: Entrevista não encontrada

components:
  schemas:
    InterviewCreate:
      type: object
      required:
        - topic_name
      properties:
        topic_name:
          type: string
        synth_ids:
          type: array
          items:
            type: string
          description: IDs dos synths a entrevistar. Se vazio, seleciona aleatoriamente.
        synth_count:
          type: integer
          default: 5
          description: Quantidade de synths se synth_ids não fornecido
        model:
          type: string
          default: gpt-4o-mini
        max_turns:
          type: integer
          default: 6
        additional_context:
          type: string
          description: Contexto adicional para o entrevistador

    InterviewResponse:
      type: object
      properties:
        exec_id:
          type: string
        experiment_id:
          type: string
        topic_name:
          type: string
        status:
          type: string
          enum: [pending, running, generating_summary, completed, failed]
        synth_count:
          type: integer
        successful_count:
          type: integer
        failed_count:
          type: integer
        model:
          type: string
        max_turns:
          type: integer
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
        has_summary:
          type: boolean

    InterviewDetailResponse:
      allOf:
        - $ref: '#/components/schemas/InterviewResponse'
        - type: object
          properties:
            summary_content:
              type: string
            transcripts:
              type: array
              items:
                $ref: '#/components/schemas/TranscriptSummary'

    InterviewListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/InterviewResponse'
        pagination:
          type: object
          properties:
            total:
              type: integer
            limit:
              type: integer
            offset:
              type: integer
            has_more:
              type: boolean

    TranscriptSummary:
      type: object
      properties:
        id:
          type: string
        synth_id:
          type: string
        synth_name:
          type: string
        status:
          type: string
        turn_count:
          type: integer

    TranscriptResponse:
      type: object
      properties:
        id:
          type: string
        synth_id:
          type: string
        synth_name:
          type: string
        status:
          type: string
        turn_count:
          type: integer
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        timestamp:
          type: string
          format: date-time

    TranscriptListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/TranscriptResponse'
        pagination:
          type: object
          properties:
            total:
              type: integer
            limit:
              type: integer
            offset:
              type: integer
            has_more:
              type: boolean

    Message:
      type: object
      properties:
        speaker:
          type: string
          enum: [Interviewer, Interviewee]
        text:
          type: string
        internal_notes:
          type: string

    # SSE Event schemas
    MessageEvent:
      type: object
      description: "event: message"
      properties:
        event_type:
          type: string
          const: message
        exec_id:
          type: string
        synth_id:
          type: string
        turn_number:
          type: integer
        speaker:
          type: string
          enum: [Interviewer, Interviewee]
        text:
          type: string
        timestamp:
          type: string
          format: date-time
        is_replay:
          type: boolean
          description: true se é replay de mensagem histórica

    InterviewCompletedEvent:
      type: object
      description: "event: interview_completed"
      properties:
        synth_id:
          type: string
        total_turns:
          type: integer

    TranscriptionCompletedEvent:
      type: object
      description: "event: transcription_completed"
      properties:
        successful_count:
          type: integer
        failed_count:
          type: integer

    ExecutionCompletedEvent:
      type: object
      description: "event: execution_completed"
      properties:
        status:
          type: string
